### ISSUE TITLE
Proper monospace braille symbols?

### ISSUE THREAD

**Issue by GTG3000** [tonsky/FiraCode#1130] opened 2020-09-28 07:11 UTC
Using the .woff2 normal version of the latest release, the braille symbols aren't monospace.
The lines in screenshot are the same length symbol-wise.
![image](https://user-images.githubusercontent.com/1013083/94401103-bc2e9100-0172-11eb-82a0-f4d73482789d.png)

Aside from their actual purpose, the braille symbols are really nice for pseudo-graphics in the console output like graphs and the like, would really appreciate support.

**Comment by pyproman** [comment] 2020-09-28 08:28
The braille characters are not supported yet in Fira Code. Similar issues: #1040 #1128

**Comment by tonsky** [comment] 2020-10-10 20:43
Closing as a duplicate of #1040 #1128

**Closed by tonsky** 2020-10-10 20:43 UTC
