### ISSUE TITLE
box alignment

### ISSUE THREAD

**Issue by chrisdrackett** [tonsky/FiraCode#725] opened 2019-03-13 19:00 UTC
It seems the alignment of some box characters is off:

![https://cl.ly/fd348a3bcd55/Screen%20Shot%202019-03-13%20at%2011.59.42%20AM.png](https://cl.ly/fd348a3bcd55/Screen%20Shot%202019-03-13%20at%2011.59.42%20AM.png)

```
   ╭───────────────────────────────────────────────────────────────╮
   │                                                               │
   │       New minor version of npm available! 6.5.0 → 6.9.0       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.9.0   │
   │               Run npm install -g npm to update!               │
   │                                                               │
   ╰───────────────────────────────────────────────────────────────╯
```

**Comment by tonsky** [comment] 2019-03-13 20:56
Duplicate of https://github.com/tonsky/FiraCode/issues/714

**Closed by tonsky** 2019-03-13 20:56 UTC

**Comment by chrisdrackett** [comment] 2019-03-13 21:00
ha, I saw that issue but had no idea if it was the same thing :)
