### ISSUE TITLE
Some ligatures are not working.

### ISSUE THREAD

**Issue by zjuwyz** [tonsky/FiraCode#395] opened 2017-03-26 02:28 UTC
![default](https://cloud.githubusercontent.com/assets/23721285/24327931/a1cf14f2-120f-11e7-9677-6a4ac2fc7152.png)
Most of the ligatures works well, but those contains  '-' characters do not.
It's the latest version of Fira Code. I'm using visual studio 2017, with ReSharper and Text sharp on Windows 10.

**Comment by wopian** [comment] 2017-03-26 02:44
Possibly a duplicate of https://github.com/tonsky/FiraCode/issues/259

**Comment by zjuwyz** [comment] 2017-03-26 02:45
Oh, Thanks XD

**Closed** 2017-03-26 02:50 UTC
