### ISSUE TITLE
 >->->>> is displayed completely wrong

### ISSUE THREAD

**Issue by MarcCoquand** [tonsky/FiraCode#596] opened 2018-05-16 17:08 UTC
In VSCode 1.22.2 if I write >->->>> it instead gets displayed as <*>->>>. I don't know why you'd ever do that operator but it's still a strange bug.

**Comment by bmamouri** [comment] 2018-05-17 03:55
Can reproduce in neither 1.21.1 nor 1.23.1 on a Mac. I don't have 1.22.2, but I wasn't able to reproduce this in any other editor.

**Comment by Regalian** [comment] 2018-05-17 11:31
I can reproduce this in 1.23.1 on a Mac running High Sierra 10.13.4

It depends on the file type selected. A rough sampling shows that
pip-requirements, Batch & CSS display as >->->>> but HTML, Java, C, C#,
C++, Elm, JavaScript display as <*>->>>

On 17 May 2018 at 04:55:15, Baqer Mamouri (notifications@github.com) wrote:

Can reproduce in neither 1.21.1 nor 1.23.1 on a Mac. I don't have 1.22.2,
but I wasn't able to reproduce this in any other editor.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tonsky/FiraCode/issues/596#issuecomment-389736789>, or mute
the thread

**Comment by mattgrande** [comment] 2018-05-17 16:32
@chocolatemelt - Strange, I'm seeing it in VS Code, but not iTerm2...

**Comment by chocolatemelt** [comment] 2018-05-17 16:35
it's pretty bizarre. losing focus bugs it out (as does copy pasting it). typing it out normally seems to have no effect

https://i.imgur.com/QhWRUcA.png

iterm2 3.1.6

**Comment by Regalian** [comment] 2018-05-18 15:28
I can confirm Atom 1.27.0 and iTerm2 3.1.6 and add Brackets 1.12, Xcode
9.3.1, Visual Studio Community 9.4, Coda 2.6.10 all on High Sierra 10.13.4

On 17 May 2018 at 17:35:41, Kevin Zhang (notifications@github.com) wrote:

it's pretty bizarre. losing focus bugs it out (as does copy pasting it).
typing it out normally seems to have no effect

https://i.imgur.com/QhWRUcA.png

iterm2 3.1.6

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tonsky/FiraCode/issues/596#issuecomment-389930003>, or mute
the thread

**Comment by tonsky** [comment] 2018-09-30 19:58
Should be fixed in 1.206

**Closed by tonsky** 2018-09-30 19:58 UTC
Labels: bug
