### ISSUE TITLE
Line spacing inhomogeneous depending on characters used

### ISSUE THREAD

**Issue by twwwt** [tonsky/FiraCode#459] opened 2017-07-22 13:09 UTC
I'm not sure whether it is actually a problem of the font (or of how it is rendered), but the line spacing is sometimes inhomogeneous. Take as an example the following two images. Note the difference in line space between the second, third, and fourth line, which, in this example, is caused by the presence/absence of `{`.

<img width="839" alt="sbi_-_atlas-core_src_main_java_ch_sbi_atlas_promos_symbol_predicate_java_-_eclipse" src="https://user-images.githubusercontent.com/143208/28491288-edddc1ea-6eee-11e7-80d8-30d14ca91e3e.png">

<img width="725" alt="sbi_-_atlas-core_src_main_java_ch_sbi_atlas_promos_symbol_predicate_java_-_eclipse" src="https://user-images.githubusercontent.com/143208/28491321-636f95aa-6eef-11e7-9af0-d9d00f6756c1.png">

**Comment by tonsky** [comment] 2017-07-22 23:20
Can you isolate the issue? Single character, nothing on prev/next line?
What OS are you using? What editor?
Do you have the same problem with other fonts? With Fira Mono?

**Comment by twwwt** [comment] 2017-07-23 09:20
It seems that bold face has a different baseline than at least normal and light face. I see this on OS X 10.12.6 using Eclipse Oxygen 4.7.0.

<img width="147" alt="sbi_-_atlas-core_src_main_java_ch_sbi_atlas_promos_symbol_predicate_java_-_eclipse" src="https://user-images.githubusercontent.com/143208/28498098-b1d1abc8-6f96-11e7-8c1b-5b63a87d98b1.png">

Note however that I don't see this behavior in that version of Eclipse using other fonts.

I've tried verifying it in other editors on the same machine but couldn't actually fine one whose syntax highlighting considers using bold face. Using Mac's Terminal app however seems to work:

<img width="39" alt="tmo_px1____ _ssh_px1_ _160x30" src="https://user-images.githubusercontent.com/143208/28498058-1bd5cf6e-6f96-11e7-8b59-764d9470f736.png">

**Comment by dhouck** [comment] 2017-07-24 15:03
I’ve seen a lot of issues with bold in Eclipse, with different fonts. I haven’t seen a baseline difference, but I’ve used monospace fonts where Eclipse rendered the bold as a different character width.

I don’t know if this is a similar issue, but there’s at least a chance it’s part of Eclipse’s bold being broken.

**Comment by DivineDominion** [comment] 2017-07-27 07:29
I just noticed this, too. Fira Mono's bold typeface appears to be larger, see https://github.com/carrois/Fira/issues/14 and the screen shot from there:

![screen shot 2017-07-27 at 09 17 59](https://user-images.githubusercontent.com/59080/28659002-151d0334-72ae-11e7-819d-31a4036a624c.png)

Fire Code has a lot more weights, and instead of emboldening the normal weight, it might work to use a lighter weight by default and use the "medium" weight as a replacement for "bold" to achieve a similar contrast.

But it would of course be even better if Fira Code's weights appeared homogenous :)

**Comment by twwwt** [comment] 2017-07-27 17:23
@dhouck I'm not sure Eclipse is broken in this regard, simply because there *are* fonts that work. Would it mean that those fonts that work are kind of inversely broken such that combined with Eclipse's brokenness they cancel out their problems? Probably not. Do you know of issues that have been filed against Eclipse's bug tracking system about this?
The conclusion to me is that inhomogeneous line spacing must be related to Fira Code. Whether it is related to Fira Code only - I don't know.

**Comment by dhouck** [comment] 2017-07-27 20:55
My experience with Eclipse had the problem with pretty much all fonts I tried and I think there was something broken with its underlying rendering. That might be a completely unrelated issue, especially if you can get most other fonts to work.

I didn’t file a report at the time, and since then I’ve change my setup. I’m not using Eclipse anymore, so I can’t reproduce it to file a report.

**Comment by DivineDominion** [comment] 2017-07-29 08:14
Just wanted to chime in again and say that it indeed appears to be a _font_ related setting that Eclipse simply does not mitigate. At least on Mac, that is. Is reproducible in macOS's TextEdit, too, and vanilla self-made apps that do not mangle with the baseline.

**Comment by tonsky** [comment] 2017-08-07 13:16
I remember trying to fix the bold height but my kung-fu is too weak. As far as I remember Fira Mono has the same problem, and in the editor both weights has identical metrics

**Comment by sarahgerweck** [comment] 2018-10-01 19:05
I also see this issue in Eclipse with Fira Code, but not with Consolas, Menlo, Courier, Courier New or Lucida Console. It's too bad because Fira Code is otherwise gorgeous.

**Comment by Holzschneider** [comment] 2018-10-03 13:14
For me, this issue only affects the bold font face. Unfortunately, Eclipse does not allow the medium font face to be used for keyword highlighting instead (which is bold enough for my taste). So as a quick fix I edited the fontface field of the medium font to say "bold" and swapped it with the flawed bold font face.

**Comment by waszqba** [comment] 2019-03-24 19:38
Hi @tonsky , I was just about to create a new issue when I found this one. 
I found out that depending on line content the spacing is sometimes is inconsistent. I am working on cLion on macOS Mojave with ligatures on.
Though I'm not sure if this has to do with Fira code or Fira in particular.
Please, let me know if I should to ask for help on Mozilla's GitHub or could it be related to your font only?

improper:
<img width="163" alt="image" src="https://user-images.githubusercontent.com/25040959/54884639-c08a3780-4e73-11e9-9f23-3da628160ee3.png">
proper:
<img width="163" alt="image" src="https://user-images.githubusercontent.com/25040959/54884722-866d6580-4e74-11e9-8e16-831bc67cd476.png">


P.S. I love this font, your ligatures made my life easier. ❤️

**Comment by cfstras** [comment] 2019-06-19 15:50
Same issue as in https://github.com/mozilla/Fira/issues/168, https://github.com/tonsky/FiraCode/issues/252

**Comment by tonsky** [comment] 2019-09-10 09:56
Should be fixed in v2

**Closed by tonsky** 2019-09-10 09:56 UTC
