### ISSUE TITLE
Block characters are too tall

### ISSUE THREAD

**Issue by SamusAranX** [tonsky/FiraCode#449] opened 2017-07-07 18:00 UTC
...at least in iTerm 2 and Terminal.app, which are the only ligature-supporting, frequently-used apps that I have.

![Screenshot of iTerm 2 displaying a bunch of text, including a progress bar made of block characters](https://user-images.githubusercontent.com/676069/27968989-75f48c96-6349-11e7-98fe-4100f32c05c0.png)
![Another screenshot of iTerm 2, this time displaying all block characters in a row above a line of text that's being clipped by them](https://user-images.githubusercontent.com/676069/27969901-10f53d5a-634d-11e7-8eac-e2b2aef4e261.png)

Fira Mono has the same problem, but this repo seems to be a little more active, so I'm opening the issue here.

**Comment by tonsky** [comment] 2017-07-07 19:26
Thanks for reporting this! I’ll see what I can do. Wouldn’t they make vertical gaps if I make them shorter though?

**Comment by SamusAranX** [comment] 2017-07-07 20:38
If Apple's font designers don't have to worry about multiple lines of block chars having vertical gaps, you shouldn't have to, either.
Let's take a look at █ U+2588 FULL BLOCK, repeated a bunch of times with different Apple-made fonts:

Monaco, by Apple (ew gross)
![blocks_monaco](https://user-images.githubusercontent.com/676069/27975498-a9761e72-6362-11e7-8eab-0ed12e22a412.png)

Menlo, by Apple (thoroughly _okay_)
![blocks_menlo](https://user-images.githubusercontent.com/676069/27975503-ae8b1688-6362-11e7-890c-90c1f5f36bce.png)

SF Mono, by Apple (still good, imho)
![blocks_sfmono](https://user-images.githubusercontent.com/676069/27975519-c4c2a04c-6362-11e7-9b4e-984e0fe82c7f.png)

Fira Code (_nice_, but a bit too tall)
![blocks_firacode](https://user-images.githubusercontent.com/676069/27975580-28da0e12-6363-11e7-9672-67b700916598.png)

**Comment by jmcs** [comment] 2017-09-27 11:44
I read FULL BLOCK as really being full vertical height (the keyword here being full). Apple Designers are not gods and their word is not gospel.

**Comment by ctongfei** [comment] 2018-03-03 22:09
Yes, this influences the visual effects of progressbars using unicode block symbols.

**Comment by YaLTeR** [comment] 2019-08-07 17:16
The same can be seen on the vertical line . They are actually so tall they visibly overlap which doesn't look good. Look for the small bolder pieces where the stacked vertical lines join. Test file:
```
 ╭──
 │
 │
 │
 ╰──
     █
│││││││█
  UO █ 
```
Screenshots from `otf-fira-code-git` from commit 7a5965a:
- `pango-view`:
![image](https://user-images.githubusercontent.com/1794388/62642743-4080dd80-b8fb-11e9-819b-77984c796350.png)
- Alacritty:
![image](https://user-images.githubusercontent.com/1794388/62642941-a2d9de00-b8fb-11e9-8b79-687f0fa79d59.png)
![image](https://user-images.githubusercontent.com/1794388/62642954-a66d6500-b8fb-11e9-8ee8-713c91c17db8.png)
- Firefox Nightly:
![image](https://user-images.githubusercontent.com/1794388/62643018-d87ec700-b8fb-11e9-9803-25876b927d45.png)
![image](https://user-images.githubusercontent.com/1794388/62643058-f0eee180-b8fb-11e9-82b2-d2f69a9c8591.png)
- `gucharmap`:
![image](https://user-images.githubusercontent.com/1794388/62643096-0b28bf80-b8fc-11e9-854b-51897ad01715.png)

When combined with full blocks to draw TUI the overlap is extremely noticable:
![image](https://user-images.githubusercontent.com/1794388/62643217-50e58800-b8fc-11e9-9568-03e558ddc990.png)
![image](https://user-images.githubusercontent.com/1794388/62643235-5e027700-b8fc-11e9-991b-0dbe85aed692.png)
![image](https://user-images.githubusercontent.com/1794388/62643248-622e9480-b8fc-11e9-8b80-871073e3f8ba.png)
![image](https://user-images.githubusercontent.com/1794388/62643259-68bd0c00-b8fc-11e9-9841-41371628f812.png)

**Comment by tonsky** [comment] 2019-08-09 11:49
Last time I looked into this it seemed different terminals/editors used different means to calculate font width. Also, some users (me included) intentionally increase line height for better readability. But I agree that overlapping lines look kind of ugly. Maybe it’s worth another look

**Comment by tonsky** [comment] 2019-08-15 13:16
Interesting problem. So if I make box-drawing characters go up/down exactly to font metrics, it’s slightly not enough. I suspect that’s because editors have to round font metrics to non-fractional amount of pixels and that’s always slightly more than font metrics suggest.

This is Sublime Text 3 on macOS with Fira Code Retina 13px. Parens on the left were adjusted to not go outside font metrics. Parens on the right have previous behaviour (they overlap by quite a lot, and you can see it as @YaLTeR mentioned)

<img width="185" alt="Screenshot 2019-08-15 at 15 52 11" src="https://user-images.githubusercontent.com/285292/63096577-f17c1d80-bf76-11e9-8b32-535e7cb07cad.png">

Another issue is that e.g. VS Code computes font height differently for some reason:

<img width="201" alt="Screenshot 2019-08-15 at 16 09 45" src="https://user-images.githubusercontent.com/285292/63096653-1ec8cb80-bf77-11e9-821a-5bb3df838cc2.png">

Same font, same size, but gaps are bigger!

So I’m afraid, sadly, there’s no right answer :( You either commit to gaps or have overlaps that render not that great at all.

**Comment by YaLTeR** [comment] 2019-08-15 15:09
There's an argument to be made here that if the editors are rendering full blocks with gaps then it's an issue of the respective editors and should be fixed on that side. I personally think that characters  out in TUIs is a worse issue (and in this case I'm afraid the font gets the blame because the characters are indeed too large).

Could you upload a test version with correct full blocks so I could check how it looks in my applications?

**Comment by tonsky** [comment] 2019-08-29 19:24
@YaLTeR and everyone interested: please try those https://github.com/tonsky/FiraCode/tree/b32369cb03ad3c0fe43fd30fd19427169e9592dc/distr/otf

I removed the overlap on full blocks and the rest of [Block elements](https://unicode-table.com/en/blocks/block-elements/) since it’s often used in progress-bar etc. I left overlap in the [Box Drawing block](https://unicode-table.com/en/blocks/box-drawing/) as those are rarely used on their own, I think it looks worse without the overlap and removing overlap would make text-based UIs look worse.

I slightly tuned UPM (2000->1950) so that Fira Code 13px would match pixel grid perfectly.

Let me know what you think.

<img width="562" alt="Screenshot 2019-08-30 at 02 21 44" src="https://user-images.githubusercontent.com/285292/63969947-2fc42180-cacd-11e9-9d9b-0c7e993bd1bb.png">

**Comment by YaLTeR** [comment] 2019-08-29 19:37
It's nice to see perfect alignment on full blocks! :+1:
![image](https://user-images.githubusercontent.com/1794388/63970739-be975680-ca59-11e9-8e39-6984aab022bd.png)

However all of the TUI overlaps are still present because they are caused by the box drawing characters being too long. :/
![image](https://user-images.githubusercontent.com/1794388/63970583-62cccd80-ca59-11e9-8378-76267c58709a.png)
![image](https://user-images.githubusercontent.com/1794388/63970594-682a1800-ca59-11e9-93d5-96818078fab3.png)
![image](https://user-images.githubusercontent.com/1794388/63970597-6b250880-ca59-11e9-9745-127e15795ae1.png)
![image](https://user-images.githubusercontent.com/1794388/63970605-70825300-ca59-11e9-93be-16f3af6637c6.png)

**Comment by tonsky** [comment] 2019-08-30 10:50
> However all of the TUI overlaps are still present because they are caused by the box drawing characters being too long. :/

Yes but you are not supposed to use them like this are you? If you want to end the line midway there are glyphs for that too, e.g. https://unicode-table.com/en/2575/

**Comment by YaLTeR** [comment] 2019-08-30 18:08
Hmm, maybe you're right. I can't find anything that says that these lines are intended to "connect" to full blocks without overlap. So my only remaining argument is the presence of those kind-of visible overlaps with other lines.

**Closed** 2019-09-09 17:53 UTC
Labels: metrics

**Comment by blahgeek** [comment] 2019-09-15 03:24
Thanks for the good work. But in my personal opinion, the new `|` seems too tall in normal code. Now the `||` is way taller than `&&`, which seems inconsistent. Also, some related ligatures is inconsistent to this taller `|`, like `|=`

![2019-09-15_11-24-04](https://user-images.githubusercontent.com/1308450/64916186-5fe91100-d7ab-11e9-8c11-2c1dfe5329b2.png)
