### ISSUE TITLE
{...} looks weird

### ISSUE THREAD

**Issue by jupl** [tonsky/FiraCode#402] opened 2017-04-02 22:34 UTC
When using object spread with React it looks odd:

![screen shot 2017-04-02 at 5 33 15 pm](https://cloud.githubusercontent.com/assets/2065876/24591586/863b1ee6-17ca-11e7-8de1-eb25034fa2b9.png)

**Comment by j-f1** [comment] 2017-04-02 22:48
I can’t reproduce this issue:

`{...props} {...}`

<img width="141" alt="{...props} {...}" src="https://cloud.githubusercontent.com/assets/25517624/24591654/ecf32a48-17d4-11e7-95f3-b7611ab793d5.png">

**Comment by tonsky** [comment] 2017-04-03 03:07
See https://github.com/tonsky/FiraCode#changelog. 1.202 and 1.203 doesn’t have it, 1.204 has it again. I should prob. remove it again :)

**Comment by dhouck** [comment] 2017-04-03 16:16
Would it be possible to just give `...` (and probably `..`, for good measure) priority over `{.` and `.}`? I can still think of cases where the ligature would look weird in shell even with those changes, but a lot of ligatures look weird in shell.

**Comment by tonsky** [comment] 2017-04-04 11:33
Thanks @dhouck it’s a good idea!

**Comment by Redmega** [comment] 2017-04-26 17:52
Spread operator should be connected to the object/var its spreading. Right now it looks like this: 

<img width="108" alt="FiraCode spread operator" src="https://cloud.githubusercontent.com/assets/662951/25448746/7eae9034-2a87-11e7-81a9-6ddf04a3e5f4.png">

However this is javascript specific. I am not sure if any other languages make use of spread like this. It might be used as an ellipsis... However, what use would there be for an ellipsis if this is not meant for text? Anyway, I digress.

**Comment by j-f1** [comment] 2017-04-26 17:59
@Redmega The problem is that Fira Code can’t tell if the text next to it is a letter, because it’s in a different HTML element.

**Comment by Redmega** [comment] 2017-04-26 18:30
> because it’s in a different HTML element.

Can you explain what you mean by that? Not following.

For the record, `[...[1,2,3]]` is valid as well, so it wouldn't only be letters.

**Comment by j-f1** [comment] 2017-04-26 18:44
Most ligatures don’t work between two highlighting colors. It looks like you are using Atom, so if you right-click on the `...` and choose “Inspect Element,” you’ll see they’re in different elements.

**Comment by Redmega** [comment] 2017-04-26 18:55
Ahh ok. I understand now. So normally they would be connected but it's my theme that's causing it to become disconnected? I'll look into changing it.

**Comment by dhouck** [comment] 2017-04-26 18:57
Support for putting it next to the letter isn’t implemented at the moment either, but if they’re different elements it won’t work even if it’s implemented.

Changing the theme won’t help; they will still be different elements even if they happen to display the same.

**Comment by zeg-io** [comment] 2017-04-27 14:30
I actually like the ... being separated doesn't matter to me whether it's a spread or not.  Makes it easier to read in any case!  Keep it as is!  Yay for Fira Code!

**Comment by jupl** [comment] 2017-04-28 21:42
I do agree that it should stay in the middle instead of right aligned. [There's other languages that use the ellipsis besides the JS spread.](https://en.wikipedia.org/wiki/Ellipsis_(computer_programming))

**Comment by Redmega** [comment] 2017-04-28 22:17
Thanks @jupl, interesting to know!  I knew the ruby one but it slipped my mind.

**Comment by tonsky** [comment] 2018-09-30 21:12
Should be fixed in 1.206, see #635

**Closed by tonsky** 2018-09-30 21:12 UTC
