### ISSUE TITLE
Can you add support for logical AND and OR operators?

### ISSUE THREAD

**Issue by jecs-imperial** [tonsky/FiraCode#810] opened 2019-08-08 16:48 UTC
I guess `/\` for AND and `\/` for OR? Also, possibly, negation? My desktop keyboard has a top left key which with shift gives `¬`, however I'm not sure all keyboards have this. I can't' think of a suitable ligature for this one.

**Comment by tonsky** [comment] 2019-08-09 11:47
I’m pretty sure those were asked before but I can’t seem to find them atm. The problem here is that those would conflict with regexp and string escapes, which are way more popular in programming than math logic. I’ll keep the issue around in case we eventually can enable those in custom font builds. Thanks for reporting!

**Comment by alexeyten** [comment] 2019-08-09 12:04
What language uses `\/` and `/\` as operators?

There are unicode symbols `&#8743;` (&#8743;) and `&#8744;` (&#8744;)

**Comment by djalbat** [comment] 2019-08-09 14:54
@tonsky, many thanks! I take your point, they are not that commonplace if at all. Custom builds at some point would be awesome.

**Comment by tonsky** [comment] 2019-09-02 17:28
Dupe of #738

**Closed by tonsky** 2019-09-02 17:28 UTC
Labels: stylistic sets, suggestion
