### ISSUE TITLE
Logical symbols

### ISSUE THREAD

**Issue by RubenVerg** [tonsky/FiraCode#794] opened 2019-07-17 10:05 UTC
Support for `\/` (`∨`), `/\` (`∧`), `^\/` (`⊻`), `!/\` (`⊼`), `!\/` (`⊽`), maybe `~` (`¬`) because `!` is too false-positivey.

I really use fira code for logic as of the natural `->` and `=>`, as well as `===`

**Comment by RubenVerg** [comment] 2019-07-17 10:05
Ik most were posted, please link them .~.

**Comment by RubenVerg** [comment] 2019-07-17 10:14
#738 found

**Comment by RubenVerg** [comment] 2019-07-17 10:15
Oh yeah regexp mess... Well actually not cuz if they are just joined ( /\ instead of / \ ) you can still read as / \ easily.

**Comment by tonsky** [comment] 2019-07-17 11:25
Duplicate of #738

**Closed by tonsky** 2019-07-17 11:25 UTC
