### ISSUE TITLE
Feature Request: Provide font variant with slashed zero instead of dotted zero

### ISSUE THREAD

**Issue by k0pernikus** [tonsky/FiraCode#481] opened 2017-08-29 09:50 UTC
I prefer the visual clarity of a dotted zero over the dotted one.

Compare Fira Code vs Meslo DZ:

![selection_044](https://user-images.githubusercontent.com/436935/29815161-f81386fc-8caf-11e7-8c54-5349bb089822.png)

In this example, the comparision between 8 and 0 might seem forced, yet esp. on small fonts or on certain colored foreground and background color combination, one can mistake them.

I would highely appreciate the option to chose and hence I kindly ask for a font variant of Fira Code with da Dashed Zero.

**Comment by tonsky** [comment] 2017-08-29 13:44
Duplicate of https://github.com/tonsky/FiraCode/issues/342

It’s actually in the font, you can enable it through opentype features or with css through `font-feature-settings: "zero" 1, "liga" on;`

**Comment by k0pernikus** [comment] 2017-08-29 14:00
@tonsky Could you please explicate how I can activate it? I have installed the font on my Ubuntu system and have set it to be used in my terminal / IDE.

**Comment by tonsky** [comment] 2017-08-29 14:25
Depends on an editor. In web-based (atom), add that line to the editor stylesheet. In other editors, I’m not sure if that’s possible

**Comment by YourFin** [comment] 2017-10-05 00:22
I have a version [in my dotfiles](github.com/yourfin/dotfiles) with slashed zeros by default. Note that this zero is not the included one, but one with a line that I put in by hand. Here's an example:
![scrollback](https://user-images.githubusercontent.com/21090009/31205794-4a30a104-a939-11e7-8053-c1c4eb5468f2.png)

**Comment by k0pernikus** [comment] 2017-10-06 10:31
@YourFin I think  you to wanted to [link  this repository](https://github.com/YourFin/dotfiles)

Furthermore, I only [find a reference to your FiraHacked](https://github.com/YourFin/dotfiles/search?utf8=✓&q=Fira&type=), not the font file itself. Could you please add it there?

**Comment by dmitriyK1** [comment] 2017-11-09 20:15
@k0pernikus 

I created a slashed zero variant:
https://github.com/dmitriyK1/FiraCodeSlashedZero

**Comment by YourFin** [comment] 2017-11-11 19:13
@k0pernikus whoops sorry, it should be in the root of the repo if you're still looking for it

**Closed** 2018-02-27 13:44 UTC
