### ISSUE TITLE
Some ligature don't work in Visual Studio 2017

### ISSUE THREAD

**Issue by davidtme** [tonsky/FiraCode#422] opened 2017-05-18 15:18 UTC
Most are ok but seems ones with a dash (-) don't

![image](https://cloud.githubusercontent.com/assets/1804141/26209720/7eb72586-3be5-11e7-8b1f-27c1c8e8c504.png)

**Comment by dhouck** [comment] 2017-05-18 15:37
This is a duplicate of #32, #43, #99, #157, #196, #220, #259, #273, and #395.

Of those, #259 has the best information. This is a bug in the editor used in Visual Studio. Microsoft knows about the issue but has not yet addressed it. There is nothing a font can do to fix it.

At this point, I’m starting to think the real issue for the font is that we could document this better so people know before downloading.

**Closed** 2017-05-18 18:44 UTC

**Comment by kizerkizer** [comment] 2019-11-21 22:50
Is this still an issue in the latest VS?

**Comment by Gaztin** [comment] 2019-11-22 07:43
> 
> 
> Is this still an issue in the latest VS?

Yes this is still an issue in VS 2019 as of version 16.3.10

**Comment by Charlie-zzy** [comment] 2020-02-09 08:57
VS 2019 version 16.3.2 find this issue as well

**Comment by stogle** [comment] 2020-02-21 14:48
> This is a duplicate of #32, #43, #99, #157, #196, #220, #259, #273, and #395.
> 
> Of those, #259 has the best information. This is a bug in the editor used in Visual Studio. Microsoft knows about the issue but has not yet addressed it. There is nothing a font can do to fix it.

They're now tracking this at https://github.com/dotnet/wpf/issues/109

**Comment by jaacko-torus** [comment] 2022-01-04 05:49
VS 2022 version 17.0.4, still an issue

**Comment by flundstrom2** [comment] 2022-03-04 09:24
VS 2022 Version 17.0.5, also issue.

**Comment by smile-zyk** [comment] 2022-10-02 11:50
VS 2022 Version 17.3.5, also issue.

**Comment by NPEX42** [comment] 2023-01-28 11:34
VS 2022 v17.4.4, Still an issue

**Comment by Stehsaer** [comment] 2023-08-25 06:19
VS 2022 v17.7.2, issue still not addressed
:-(

**Comment by wopian** [comment] 2023-08-25 07:48
This is a VS issue - you can follow the (lack of) progress here: https://github.com/dotnet/wpf/issues/109
