### ISSUE TITLE
Disjunction ligatures

### ISSUE THREAD

**Issue by channingwalton** [tonsky/FiraCode#191] opened 2016-05-25 08:39 UTC
Hi,
it would be great to support \/ as something like ∨

Thanks,

Channing

**Comment by engelfrost** [comment] 2016-05-31 09:00
What does it mean? 

I can only come up with regular expressions, but it would do more harm than good there...

`var re = /\/path\//;`

**Comment by channingwalton** [comment] 2016-05-31 09:26
It is a symbol that represents disjunction (logical OR), (see the truth table here https://en.wikipedia.org/wiki/Logical_disjunction). It appears in a widely used scala library.

I agree it would be completely wrong in regex.

**Comment by tonsky** [comment] 2019-09-02 17:28
Dupe of #738

**Closed by tonsky** 2019-09-02 17:28 UTC
Labels: stylistic sets, suggestion
