### ISSUE TITLE
=== is not equally spaced vertically in VS Code at some sizes

### ISSUE THREAD

**Issue by vaindil** [tonsky/FiraCode#683] opened 2018-11-28 19:43 UTC
Sorry, I'm not sure if this is a font issue or a VS Code issue. I use Fira Code in VS Code, and === is not equally spaced vertically at some font sizes. I'm using Windows 10, Fira Code 1.206, VS Code Insiders 1.30.0-insider, and my VS Code font is set to "Fira Code". Font weight is 300.

![sizes](https://user-images.githubusercontent.com/771134/49177669-ce8fd780-f31b-11e8-8f04-da9c10b273a8.png)

**Comment by wopian** [comment] 2018-11-29 04:14
Duplicate of #405 😃

**Comment by tonsky** [comment] 2018-11-29 15:00
Yes, it’s a know problem with Windows. Unfortunately I don’t have a solution yet

**Closed by tonsky** 2018-11-29 15:00 UTC

**Comment by vaindil** [comment] 2018-11-29 15:44
Sorry, I missed that issue. Thank you!
