### ISSUE TITLE
the letter i following the letter f

### ISSUE THREAD

**Issue by Praczet** [tonsky/FiraCode#1445] opened 2022-07-20 11:47 UTC
It is about the 'i' letter. It is rendered as it should be for all combinations expect fi

In my setting (vscode) I have like this:

`"editor.fontLigatures": "'cv06','cv02', 'ss02', 'ss03'",`

And it looks like this:
![image](https://user-images.githubusercontent.com/109667910/179974417-ba7e6328-f519-432a-90cd-31d9e816b35e.png)

**Comment by wopian** [comment] 2022-07-20 12:04
Duplicate of https://github.com/tonsky/FiraCode/issues/1317

**Closed** 2022-07-24 13:28 UTC
