### ISSUE TITLE
Opinion about 'r' -> what's yout opinion?

### ISSUE THREAD

**Issue by byoungju94** [tonsky/FiraCode#718] opened 2019-02-19 02:47 UTC
I think fira code medium is a perfect font.

in windows, another font is thin, and hurts my eyes but fira code.

but I think 'r' is little awkward...

does anybody feel same with me? or only me...

**Comment by j-f1** [comment] 2019-02-19 13:46
Duplicate of #601

**Comment by abductedMind** [comment] 2019-05-06 10:18
But are the down votes above because of disagreement or knowledge of the other issue where many people would thumbs up the above?

**Closed** 2019-08-27 12:08 UTC
