### ISSUE TITLE
Remove/change ~= ?

### ISSUE THREAD

**Issue by daurnimator** [tonsky/FiraCode#381] opened 2017-03-19 12:09 UTC
FiraCode renders the `~=` ligature like asymptotically equal to (U+2243: ≃).

In lua and MATLAB, `~=` is not equal to.
Historical context: I believe `~` was chosen as it is the closest ascii character to the not sign (U+00AC: ¬)

**Comment by roryokane** [comment] 2017-04-03 16:57
I wondered if this change would affect the Perl/Ruby regex match operator, but [that’s `=~`](https://ruby-doc.org/core-2.4.1/String.html#method-i-3D-7E), not `~=`.

**Comment by dhouck** [comment] 2017-04-03 19:00
Is there any language where `~=` means ≃?

**Comment by mcepl** [comment] 2017-09-12 19:24
Which way the duplicate goes? Is this duplicate of #293 or vice versa?

**Comment by dhouck** [comment] 2017-09-12 19:53
No; that’s about `=~` and this is about `~=`.

**Comment by MadcapJake** [comment] 2017-09-12 22:05
Also Dylan, Smalltalk, and BCPL use `~=` to mean `not equal to`. Perl 6 uses [`=~=`](https://docs.perl6.org/language/operators.html#infix_=~=) for the approx-equal operator.

**Comment by daurnimator** [comment] 2018-04-06 06:55
*bump*, should someone send a PR removing it?

**Comment by tonsky** [comment] 2018-04-06 08:34
I’ll remove it from the next release

**Comment by Lixquid** [comment] 2019-11-06 13:37
Now that stylistic sets are supported, it'd be great to see this as a stylistic set!

**Closed** 2020-04-05 22:35 UTC
Labels: conflict, stylistic sets
