### ISSUE TITLE
[Suggestion] Lua ~= operator ligature

### ISSUE THREAD

**Issue by dinispimentel** [tonsky/FiraCode#1415] opened 2022-05-23 23:31 UTC
Just wanted to propose the same ligature of `!=` combo (or a new design) to the `~=` combo, because in Lua the **not equal operator** is `~=`.

I know it is not a major change, but I would appreciate it. Please let me know if it can be implemented.

Thanks in advance.

**Comment by rikkimax** [comment] 2022-05-23 23:34
D uses ``~=`` for appending to an array.

**Comment by wopian** [comment] 2022-05-24 09:51
Duplicate of https://github.com/tonsky/FiraCode/issues/1186

**Comment by tonsky** [comment] 2022-05-24 11:03
Will close as duplicate

**Closed by tonsky** 2022-05-24 11:03 UTC
