### ISSUE TITLE
+= -= *= /= %=

### ISSUE THREAD

**Issue by RubenVerg** [tonsky/FiraCode#793] opened 2019-07-17 08:55 UTC
I know there are 10000000 posts bout this.
I just have an idea of how to show them.
`+=` with the plus' right bar slightly inserted in the space between the two bars of the `=`. Same with `-=` and `*=`. For `/=` and `%=`, the bar should be touching equals and the bottom bar of equals slightly longer

**Comment by tonsky** [comment] 2019-07-17 11:25
Duplicate of #655

**Closed by tonsky** 2019-07-17 11:25 UTC
