### ISSUE TITLE
Ligature Request: /\

### ISSUE THREAD

**Issue by ghivert** [tonsky/FiraCode#488] opened 2017-09-14 21:23 UTC
Hi!

We have in PureScript the operator `/\` as separator for tuples elements separator.
Would be good to have it in the font! :)

Thanks so much for such a beautiful font!

**Comment by MadcapJake** [comment] 2017-09-15 00:39
AFAICT, the operator is [actually](https://github.com/purescript/documentation/blob/9ac3a04fdf750b7ea5b702da7b12027ebb36136a/language/Differences-from-Haskell.md#tuples) apart of a PureScript [package](https://pursuit.purescript.org/packages/purescript-tuples/4.1.0/docs/Data.Tuple.Nested).

However, (the ancient) BCPL uses `/\` for the logical-and operator and `\/` for the logical-or operator (in a nod to first-order logic).

**Comment by tonsky** [comment] 2017-09-15 06:42
There was already a suggestion about that, unfortunately, it’ll probably conflict a lot with escaped slash and regex definitions

**Comment by foreverbell** [comment] 2017-10-31 16:22
This would be great for some automated theorem provers like Coq.

**Comment by tonsky** [comment] 2019-09-02 17:28
Dupe of #738

**Closed by tonsky** 2019-09-02 17:28 UTC
Labels: stylistic sets
